sudo: required
servies:
  - dockertravis ci no green dot

#build test container
before_install:
  - docker build -t jaredwmitchell/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jaredwmitchell/react-test npm run test -- --coverage

#build images
after_success:
  - docker build -t jaredwmitchell/multi-client ./client
  - docker build -t jaredwmitchell/multi-nginx ./nginx
  - docker build -t jaredwmitchell/multi-server ./server
  - docker build -t jaredwmitchell/multi-worker ./worker

#login to docker-cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#push images to docker hub
  - docker push jaredwmitchell/multi-client
  - docker push jaredwmitchell/multi-nginx
  - docker push jaredwmitchell/multi-server
  - docker push jaredwmitchell/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker" 
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-409751379112"
  bucket_path: "multi-docker"
  on:
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
